apiVersion: v1
kind: Secret
metadata:
  name: erp-secret
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  PGUSER: "elad"
  PGHOST: "erp-postgresql.default.svc.cluster.local"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: erp 
  ERP_BASE_URL: "http://erp-service:5000"