apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{.Values.name}}-client-configmap
  namespace: {{.Values.namespace}}
data:
  default.conf.template: |
      server {
        listen 80;
        location / {
        sub_filter_once on;
        sub_filter "URL_PLACEHOLDER" {{.Values.global.base_url}}/banner/api;
          root /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
        }
        location /assets/ {
          root /usr/share/nginx/html;
          try_files $uri $uri/ =404;
        }
      }