apiVersion: v1
kind: Secret
metadata:
  name: store-secret
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  PGUSER: "elad"
  PGHOST: "store-postgresql.default.svc.cluster.local"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: store 
  ERP_BASE_URL: "http://erp-service:5000"
  OMS_BASE_URL: "http://oms-service:5000"
  BANNERS_BASE_URL: "http://banners-service:5000"