apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  namespace: {{.Values.namespace}}
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  MONGO_URI: "mongodb://root:password@banner-mongodb-0.banner-mongodb-headless.{{.Values.namespace}},banner-mongodb-1.banner-mongodb-headless.{{.Values.namespace}},banner-mongodb-2.banner-mongodb-headless.{{.Values.namespace}}:27017/admin"
  PGUSER: "elad"
  PGHOST: "banner-postgresql.{{.Values.namespace}}"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "users" 
  ERP_BASE_URL: "http://erp-server-service.erp:5000"
  STORE_BASE_URL: "http://store-server-service.store:5000"
  OMS_BASE_URL: "http://oms-server-service.oms:5000"
