apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  namespace: {{.Values.namespace}}
stringData:
  PORT : "5000"
  JWT_SECRET: "ebf64db15d5c7e726491f9df6eed630a63f58027dda470e46b1de4ed1a083079c955df979d30d16189a88dd3700e18a1d9e6f0792c959c33c
  11e177b52b30a9"
  MONGO_URI: "mongodb://root:password@oms-mongodb-0.oms-mongodb-headless.{{.Values.namespace}},oms-mongodb-1.oms-mongodb-headless.{{.Values.namespace}},oms-mongodb-2.oms-mongodb-headless.{{.Values.namespace}}:27017/admin"
  PGUSER: "elad"
  PGHOST: "{{.Values.name}}-postgresql.{{.Values.namespace}}"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "users" 
  ERP_BASE_URL: "http://erp-server-service.erp:5000"
  STORE_BASE_URL: "http://store-server-service.store:5000"
  OMS_BASE_URL: "http://oms-server-service.oms:5000"
