apiVersion: v1
kind: Secret
metadata:
  name: oms-secret
stringData:
  PORT : "5000"
  #MONGO_URI: "mongodb+srv://admin:UH8T9YYp5M9gJ9n3@cluster0.7z3sfhl.mongodb.net/test?retryWrites=true&w=majority"
  ACCESS_TOKEN_SECRET: 0ebf64db15d5c7e726491f9df6eed630a63f58027dda470e46b1de4ed1a083079c955df979d30d16189a88dd3700e18a1d9e6f0792c959c33c
  MONGO_URI: "mongodb://root:password@oms-mongodb-0.oms-mongodb-headless,oms-mongodb-1.oms-mongodb-headless,oms-mongodb-2.oms-mongodb-headless:27017"
  PGUSER: "elad"
  PGHOST: "oms-postgresql.default.svc.cluster.local"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "projoms" 
  ERP_BASE_URL: "http://erp-service:5000"