apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  namespace: {{.Values.namespace}}
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  PGUSER: "elad"
  PGHOST: "erp-postgresql.{{.Values.namespace}}"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "erp" 
  BANNER_BASE_URL: "http://banner-server-service.banner:5000"
  STORE_BASE_URL: "http://store-server-service.store:5000"
  OMS_BASE_URL: "http://oms-server-service.oms:5000"