apiVersion: v1
kind: Secret
metadata:
  name: oms-secret
  namespace: oms
stringData:
  PORT : "5000"
  MONGO_URI: "mongodb://root:password@oms-mongodb-0.oms-mongodb-headless.oms,oms-mongodb-1.oms-mongodb-headless.oms,oms-mongodb-2.oms-mongodb-headless.oms:27017/admin"
  PGUSER: "elad"
  PGHOST: "oms-postgresql.oms"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "projoms"
  JWT_SECRET: "0ebf64db15d5c7e726491f9df6eed630a63f58027dda470e46b1de4ed1a083079c955df979d30d16189a88dd3700e18a1d9e6f0792c959c33c
11e177b52b30a9"