apiVersion: v1
kind: Secret
metadata:
  name: banners-secret
  namespace: banner
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  MONGO_URI: "mongodb://root:password@banners-mongodb-0.banners-mongodb-headless.banner,banners-mongodb-1.banners-mongodb-headless.banner,banners-mongodb-2.banners-mongodb-headless.banner:27017/admin"
  PGUSER: "elad"
  PGHOST: "banners-postgresql.banner"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "users" 
  ERP_BASE_URL: "http://erp-server-service.erp:5000"
  STORE_BASE_URL: "http://store-server-service.store:5000"
  OMS_BASE_URL: "http://oms-server-service.oms:5000"
