apiVersion: v1
kind: Secret
metadata:
  name: banners-secret
stringData:
  PORT : "5000"
  #MONGO_URI: "mongodb+srv://admin:UH8T9YYp5M9gJ9n3@cluster0.7z3sfhl.mongodb.net/test?retryWrites=true&w=majority"
  JWT_SECRET: "secret"
  MONGO_URI: "mongodb://root:password@banners-mongodb-0.banners-mongodb-headless,banners-mongodb-1.banners-mongodb-headless,banners-mongodb-2.banners-mongodb-headless:27017"
  PGUSER: "elad"
  PGHOST: "banners-postgresql.default.svc.cluster.local"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: "users" 
  ERP_BASE_URL: "http://erp-service:5000"
