apiVersion: apps/v1
kind: Deployment
metadata:
  name: banners-server-deployment
  namespace: banner
  labels:
    app: banners-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banners-server
  template:
    metadata:
      labels:
        app: banners-server
    spec:
      containers:
      - name: banners-server
        image: yakovda/banner-server:1.1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: banners-config
        - secretRef:
            name: banners-secret
        volumeMounts:
        - name: banner-public-storage
          mountPath: /app/public
      volumes:
        - name: banner-public-storage
          
          