apiVersion: v1
kind: Secret
metadata:
  name: store-secret
  namespace: store
stringData:
  PORT: "5000"
  JWT_SECRET: "secret"
  PGUSER: "elad"
  PGHOST: "store-postgresql.store"
  PGPORT: "5432"
  PGPASSWORD: "password"
  PGDATABASE: store 
  ERP_BASE_URL: "http://erp-server-service.erp:5000"
  OMS_BASE_URL: "http://oms-server-service.oms:5000"
  BANNER_BASE_URL: "http://banners-server-service.banner:5000"