architecture: replicaset
auth:
  enabled: true
  rootUser: root
  rootPassword: 'password'
replicaCount: 3
persistence:
  size: 1Gi
arbiter:
  enabled: false

initdbScripts:
  init-script.js: |
    try {
      db = db.getSiblingDB("admin");
      
      const orderData = {
              cartItems: [
                {
                  productId: "21",
                  name: "Produc3 1",
                  description: "Description 1",
                  salePrice: 50,
                  quantity: 2,
                  discount: 0,
                  image: {
                    url: "https://example.com/product-image.jpg",
                  },
                },
                {
                  productId: "32",
                  name: "Product XYZ",
                  description: "Description XYZ",
                  salePrice: 75,
                  quantity: 3,
                  discount: 10,
                  image: {
                    url: "https://example.com/product-xyz-image.jpg",
                  },
                },
                {
                  productId: "45",
                  name: "Special Product",
                  description: "Special Edition",
                  salePrice: 120,
                  quantity: 1,
                  discount: 5,
                  image: {
                    url: "https://example.com/special-product-image.jpg",
                  },
                },
              ],
            userId: "user21שש1",
            userName: "John yy",
            userEmail: "johan.doe@example.com",
            orderTime: "2023-11-22T12:00:00.000Z",
            status: "Waiting",
            totalPrice: 395,
            shippingDetails: {
              address: {
                country: "Israel",
                city: "Tel Aviv",
                street: "Main Street",
                zipCode: 12345,
              },
              contactNumber: "123456789",
              orderType: "SelfCollection",
            },
            contactNumber: "123456789",
          };

      db.orders.insertOne(orderData);
      print('Database seeded successfully.');
      print(db.getSiblingDB("admin").orders.countDocuments());
    } catch (err) {
      print('Error while seeding database:');
      print(err);  
    }
