global:
  postgresql:
    auth:
      username: "elad"
      password: "password"
      database: "projoms"

primary:
  initdb:
    scripts:
      pg-init.sh: |
        #!/bin/bash
        echo "Initializing database..."
        set -e
        export PGPASSWORD="$POSTGRES_PASSWORD"
        export PGUSER="$POSTGRES_USER"
        export PGDATABASE="$POSTGRES_DATABASE"

        psql -v ON_ERROR_STOP=1 <<-EOSQL

            CREATE TABLE IF NOT EXISTS admin_users (
                user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                first_name VARCHAR(50) NOT NULL,
                last_name VARCHAR(50) NOT NULL,
                email VARCHAR(100) UNIQUE NOT NULL,
                password VARCHAR(255) NOT NULL,
                is_admin BOOLEAN,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        EOSQL
        echo "Database initialized!"
